### PR TITLE
Updating index.html with new Salesforce.org messaging

### PR DESCRIPTION
**Pull request by dylanhansen**
Poking around in our GH pages site this afternoon, figured I'd update our About with the new messaging for SFDO.

### CODE REVIEW

**Comment by dylanhansen** [comment]
@jvarese Let me know if you have any concerns updating our dev site with the newest messaging from today.  Thanks!

**Comment by dylanhansen** [comment]
@jvarese Just scroll to the bottom of http://developer.salesforce.org/ and you'll see it there.  I can take a screenshot of the new content if that helps but I double checked it on my local system so it looks good, just want to see if the wording is OK.  Thanks!

**Comment by dextermilo** [comment]
@jvarese any issues with his text?

**Comment by dylanhansen** [comment]
@jvarese The content here is the same as on the job descriptions.  Any concerns if we merge this change?

**Comment by jvarese** [comment]
@dextermilo @dylanhansen - please go ahead and merge. Sorry for the delay. I've tried everything and can't seem to get github notifications.

**Pull request merged**
